### ISSUE TITLE
Spiral is shown with large number of items

### ISSUE THREAD

**Issue by sonasapps** [notsobigcompany/CardStack#1]
I have 16 cards in a test and the spiral of cards can be seen behind and trailing off to the side of the main Card Stack.

CardStack(projects) {(project: Project) in
 Image(project.image)
         .resizable()
         .cornerRadius(20)
         .frame(width: 300, height: 400)
    }

**Comment by sonasapps** [comment]
It seems to be as soon as I hit 14 items in the Stack

**Comment by simonefarenza** [comment]
Did you find any solution to that?

**Comment by thatvirtualboy** [comment]
Unfortunately not.

Other things I've noticed:
• I'm experiencing performance issues if I have 13+ images being loaded in from Core Data. Swiping back and forth a few times crashes the app.
• When using these images, while you swipe the images become translucent revealing the next images underneath which looks odd. It's not solid during the entire swipe action like in the example gif with solid colors.

**Comment by phillipcaudell** [comment]
Hello! Apologies for missing this, I had not toggled watch on this repo 😅

If you still require a solution to this, please take a look at the new BigUIPaging package, specifically CardDeckPageViewStyle. 

https://github.com/notsobigcompany/BigUIPaging

Pages are lazy loaded, so you'll get 1) improved performance and 2) no overflowing with more than 10 items. 

I'll close this issue as this package will be deprecated soon.

**Comment by simonefarenza** [comment]
Hi @phillipcaudell, I appreciate your assistance. The new library is functioning wonderfully. I was wondering if it's possible to customize the cornerRadius of the cards.

Thanks, Simone

**Comment by phillipcaudell** [comment]
Hey Simone, you sure can! Take a look at the corner radius modifier: 

https://opensource.notsobig.company/documentation/bigswiftui/swiftui/view/pageviewcardcornerradius(_:)/
