### ISSUE TITLE
change rotation degree to front

### ISSUE THREAD

**Issue by AbGhost-cyber** [notsobigcompany/CardStack#2]
Hi, massive thing you did here, i was wondering if it is possible to make the card rotate forward in such a way that we can see the bottom of other underlying cards

**Comment by henribredt** [comment]
That would be a really great addition

**Comment by phillipcaudell** [comment]
Hello! Apologies for missing this, I had not toggled watch on this repo 😅

If you still require a solution to this, please take a look at the new BigUIPaging package, specifically CardDeckPageViewStyle. It has far more configuration options available. 

https://github.com/notsobigcompany/BigUIPaging

I'll close this issue as this package will be deprecated soon.
