### ISSUE TITLE
Unrecognized selector

### ISSUE THREAD

**Issue by thatvirtualboy** [notsobigcompany/CardStack#3]
Hi Philip! Thanks again for this great package. Any idea why I'd be seeing the error

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[App.Project capturedimages]: unrecognized selector sent to instance 0x28395cd00'
terminating with uncaught exception of type NSException

`Project` is one CoreData Entity
`CapturedImage` is another
and they have an inverse relationship `project.capturedimage`

```
                                    let images = (project.capturedimages as? Set<CapturedImage>) ?? []
                                    CardStack(Array(images).sorted{$0.timestamp! > $1.timestamp!}) { capturedImage in
                                        let image = capturedImage.image.map(UIImage.init(data:))
                                        Image(uiImage: (image ?? self.projectImage1 as! UIImage)!)
                                            .resizable()
                                            .scaledToFill()
                                            .frame(width: 300, height: 420)
                                            .cornerRadius(20)
                                            .onTapGesture {
                                                let impactLight = UIImpactFeedbackGenerator(style: .light)
                                                impactLight.impactOccurred();
                                                print(project.objectID)
                                                sheet = .imageTap(project)
                                            }
                                    }
```

**Comment by phillipcaudell** [comment]
Hello! Apologies for missing this, I had not toggled watch on this repo 😅

At first glance this looks like some threading issue with your CoreData setup. Unfortunately it's a bit outside the scope of this package.

If you are still using this package, please take a look at the new BigUIPaging package, specifically CardDeckPageViewStyle.

https://github.com/notsobigcompany/BigUIPaging

This package will be deprecated soon.
